stages:
  - build
  - deploy

build:
  image: node:18.0.0
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build/

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none # Do not clone git repo
    NODE_ENV: production
    PUBLIC_URL: https://usmartai.gitlab.io/usmartai-front-end
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public